# Generated by Django 5.2.3 on 2025-06-17 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('tamaño', models.FloatField()),
                ('peso', models.FloatField()),
                ('estado_salud', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vacunas',
            fields=[
                ('perro_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='adopcion.perro')),
                ('vacuna1', models.CharField(max_length=100)),
            ],
            bases=('adopcion.perro',),
        ),
    ]
