# Generated by Django 5.2.3 on 2025-06-22 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contraseña', models.CharField(max_length=128)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('codigo_admin', models.CharField(max_length=10, unique=True)),
                ('nivel_acceso', models.CharField(default='basico', max_length=20)),
                ('puede_aprobar_adopciones', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_raza', models.CharField(max_length=30)),
                ('tamaño', models.CharField(choices=[('miniatura', 'Miniatura'), ('pequeño', 'Pequeño'), ('mediano', 'Mediano'), ('grande', 'Grande'), ('gigante', 'Gigante')], default='miniatura', max_length=10)),
                ('peso', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioAdoptante',
            fields=[
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contraseña', models.CharField(max_length=128)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('dni', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Perro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('estado_salud', models.CharField(choices=[('sano', 'Sano'), ('tratamiento', 'En tratamiento'), ('enfermo', 'Enfermo')], default='sano', max_length=50)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('reservado', 'Reservado'), ('adoptado', 'Adoptado')], default='disponible', max_length=10)),
                ('raza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adopcion.raza')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudAdopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perroelegido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adopcion.perro')),
                ('usuarioadop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adopcion.usuarioadoptante')),
            ],
        ),
        migrations.CreateModel(
            name='SistemaAdopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('confirmar', models.BooleanField(blank=True, null=True)),
                ('peticion_adopcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adopcion.solicitudadopcion')),
            ],
        ),
        migrations.CreateModel(
            name='Temperamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enojado', models.BooleanField(blank=True, null=True)),
                ('tranquilo', models.BooleanField(blank=True, null=True)),
                ('travieso', models.BooleanField(blank=True, null=True)),
                ('alegre', models.BooleanField(blank=True, null=True)),
                ('perro', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adopcion.perro')),
            ],
        ),
        migrations.CreateModel(
            name='Preferencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pref_edad', models.IntegerField()),
                ('pref_tamaño', models.CharField(choices=[('miniatura', 'Miniatura'), ('pequeño', 'Pequeño'), ('mediano', 'Mediano'), ('grande', 'Grande'), ('gigante', 'Gigante')], default='miniatura', max_length=10)),
                ('pref_raza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adopcion.raza')),
                ('pref_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adopcion.usuarioadoptante')),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adopcion_completada', models.BooleanField(default=False, verbose_name='Adopción Completada')),
                ('perro_adoptado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adopcion.perro')),
                ('fecha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adopcion.sistemaadopcion')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adopcion.usuarioadoptante')),
            ],
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moquillo_canino', models.BooleanField(blank=True, null=True)),
                ('parvovirus', models.BooleanField(blank=True, null=True)),
                ('hepatitis_infecciosa_canina', models.BooleanField(blank=True, null=True)),
                ('rabia', models.BooleanField(blank=True, null=True)),
                ('leptos_pirosis', models.BooleanField(blank=True, null=True)),
                ('perro', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adopcion.perro')),
            ],
        ),
    ]
