# Generated by Django 5.2.3 on 2025-06-17 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_raza', models.CharField(max_length=30)),
                ('tamaño', models.CharField(choices=[('miniatura', 'Miniatura'), ('pequeño', 'Pequeño'), ('mediano', 'Mediano'), ('grande', 'Grande'), ('gigante', 'Gigante')], default='miniatura', max_length=10)),
                ('peso', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='perro',
            name='peso',
        ),
        migrations.RemoveField(
            model_name='perro',
            name='tamaño',
        ),
        migrations.AddField(
            model_name='perro',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('reservado', 'Reservado'), ('adoptado', 'Adoptado')], default='disponible', max_length=10),
        ),
        migrations.AddField(
            model_name='perro',
            name='raza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adopcion.raza'),
        ),
        migrations.CreateModel(
            name='Temperamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enojado', models.BooleanField(blank=True, null=True)),
                ('tranquilo', models.BooleanField(blank=True, null=True)),
                ('travieso', models.BooleanField(blank=True, null=True)),
                ('alegre', models.BooleanField(blank=True, null=True)),
                ('perro', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adopcion.perro')),
            ],
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moquillo_canino', models.BooleanField(blank=True, null=True)),
                ('parvovirus', models.BooleanField(blank=True, null=True)),
                ('hepatitis_infecciosa_canina', models.BooleanField(blank=True, null=True)),
                ('rabia', models.BooleanField(blank=True, null=True)),
                ('leptos_pirosis', models.BooleanField(blank=True, null=True)),
                ('perro', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adopcion.perro')),
            ],
        ),
        migrations.DeleteModel(
            name='Vacunas',
        ),
    ]
