# Generated by Django 5.2.3 on 2025-06-23 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='nivel_acceso',
        ),
        migrations.RemoveField(
            model_name='usuarioadoptante',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='usuarioadoptante',
            name='telefono',
        ),
    ]
