# Generated by Django 5.2.3 on 2025-06-23 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0002_remove_administrador_nivel_acceso_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Preferencias',
        ),
    ]
