# Generated by Django 5.2.3 on 2025-06-17 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0002_raza_remove_perro_peso_remove_perro_tamaño_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioAdoptante',
            fields=[
                ('nombre_usu', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contraseña', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Preferencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pref_edad', models.IntegerField()),
                ('pref_tamaño', models.CharField(choices=[('miniatura', 'Miniatura'), ('pequeño', 'Pequeño'), ('mediano', 'Mediano'), ('grande', 'Grande'), ('gigante', 'Gigante')], default='miniatura', max_length=10)),
                ('pref_raza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adopcion.raza')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudAdopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perroelegido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adopcion.perro')),
                ('usuarioadop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adopcion.usuarioadoptante')),
            ],
        ),
        migrations.CreateModel(
            name='SistemaAdopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('confirmar', models.BooleanField(blank=True, null=True)),
                ('peticion_adopcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adopcion.solicitudadopcion')),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perro_adoptado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adopcion.perro')),
                ('histo_pref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adopcion.preferencias')),
                ('fecha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adopcion.sistemaadopcion')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adopcion.usuarioadoptante')),
            ],
        ),
    ]
