# Generated by Django 5.2.3 on 2025-06-17 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0003_usuarioadoptante_preferencias_solicitudadopcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferencias',
            name='pref_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adopcion.usuarioadoptante'),
        ),
        migrations.AlterField(
            model_name='perro',
            name='estado_salud',
            field=models.CharField(choices=[('sano', 'Sano'), ('tratamiento', 'En tratamiento'), ('enfermo', 'Enfermo')], default='sano', max_length=50),
        ),
    ]
